return {
  -- {
  --   'karb94/neoscroll.nvim',
  --   event = 'VeryLazy',
  --   opts = {
  --     -- turn off plugin’s default keymaps; we’ll define our own
  --     mappings = {},
  --     hide_cursor = false,
  --     stop_eof = true,
  --     respect_scrolloff = true,
  --     cursor_scrolls_alone = true,
  --     duration_multiplier = 1.0, -- keep at 1.0 since we set explicit durations below
  --     easing = 'sine', -- smoother, VSCode-ish
  --     performance_mode = true,
  --     ignored_events = { 'WinScrolled' },
  --   },
  --   config = function(_, opts)
  --     local neoscroll = require 'neoscroll'
  --     neoscroll.setup(opts)
  --
  --     local map, modes = vim.keymap.set, { 'n', 'v', 'x' }
  --
  --     -- Fast-but-smooth VSCode feel
  --     map(modes, '<C-u>', function()
  --       neoscroll.ctrl_u { duration = 160 }
  --     end, { desc = 'Smooth half-page up' })
  --     map(modes, '<C-d>', function()
  --       neoscroll.ctrl_d { duration = 160 }
  --     end, { desc = 'Smooth half-page down' })
  --   end,
  -- },
}
